#!/usr/bin/env node
var api= require('marvel-api')
var program = require('commander')
var colors = require('colors')
var Marvel = require('./marvel.js')

program
  .version('0.1.0')
  .option('-f, --first100', 'Give  me first 100 marvel characters')
  .parse(process.argv);

if (program.first100) {
  var marvel = new Marvel( {
    publicKey : '3d82e91fbd3d89a2a32319235b3aa3b2',
    privateKey : 'aa9a71353466ac3df782c0cfd95e2a9454517ce1'
    })
  marvel.getFirst100()  
} 



